
char *html = ""
"<html>"
"    <head>"
"        <link rel='stylesheet' href='//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/jquery-ui.css' />"
"        <script src='//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js'></script>"
"        <script src='//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js'></script>"
"        <script>"
"$(function() {"
"    $('#temp').progressbar({"
"        value:0"
"    });"
"});"
""
"$(function() {"
"    var update = function(){"
"        $.getJSON('data.json', function(data){"
"             $('#temp').progressbar('value', data['temp'])"
"        });"
"    };"
""
"    setInterval(update, 1000);"
"});"
"        </script>"
"    </head>"
"    <body>"
"        <div id='temp'></div>"
"    </body>"
"</html>";
