
char *html = ""
"<html>"
"    <head>"
"        <link rel='stylesheet' href='//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/jquery-ui.css' />"
"        <script src='//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js'></script>"
"        <script src='//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js'></script>"
"        <script>"
"$(function() {"
""
"    $( '.pbar' ).each(function(){"
"         $(this).progressbar({"
"            value:0"
"        });"
"    });"
"});"
""
"$(function() {"
"    var update = function(){"
"        $.getJSON('data.json', function(data){"
"            $.each(data, function(index, value) {"
"                $('#' + index).progressbar('value', value / 2)"
"            });"
"        });"
"    };"
""
"    setInterval(update, 1000);"
"});"
"        </script>"
"    </head>"
"    <body>"
"        <div id='A0' class='pbar'></div>"
"        <div id='A1' class='pbar'></div>"
"        <div id='A2' class='pbar'></div>"
"        <div id='A3' class='pbar'></div>"
"        <div id='A4' class='pbar'></div>"
"        <div id='A5' class='pbar'></div>"
"    </body>"
"</html>";
